# must be unique in a given SonarQube instance
sonar.projectKey=proforma-app

# --- optional properties ---
sonar.projectName=Proforma App
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=src

# Exclusiones importantes (evita analizar carpetas innecesarias)
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/dist/**,**/build/**,**/*.d.ts,**/public/**

# TypeScript configuration
sonar.typescript.tsconfigPath=tsconfig.json

# Default SonarQube server
sonar.host.url=http://localhost:9000

# Authentication token
sonar.token=squ_fa9626eb01984e6a3440827ec92693268d4fdb53

# Encoding of the source code
sonar.sourceEncoding=UTF-8